config/routes.rb
Einbeinig0r::Application.routes.draw do
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  resources :participants

  root :to => 'participants#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :born_in_year, :email, :gmail_address, :name, :phone_number, :sip_address, :skype_user, :topic_description, :topic_keywords, :gender

  validates :name, presence: true
  validates :email, presence: true
  validates :born_in_year, presence: true
  validates :topic_keywords, presence: true
  validates :topic_description, presence: true

  @email_regexp = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  validates :email, format: { with: @email_regexp, message: "Email address is invalid." }
  validates :gmail_address, format: { with: @email_regexp, message: "GMail address is invalid." }
  validates :sip_address, format: { with: @email_regexp, message: "SIP address is invalid." }

  validates :gender, inclusion: { in: ['male', 'female', 'other', 'n/a'] }

  validates :born_in_year, inclusion: { in: 1900..2100 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  def skype_link_to(text, user)
    (link_to image_tag("skype-logo.png", width: "20px", height: "20px") , "skype:#{user}?call") + " #{user}"
  end

  def sip_link_to(text, address)
    link_to text, "sip:#{address}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= I18n.t 'application_title' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
  <%= link_to I18n.t('application_title'), root_path, :class => "brand" %>
    <ul class="nav">
      <li><%= link_to I18n.t('activerecord.models.participants'), participants_path %></li>
      <li><%= link_to I18n.t('admin'), admin_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to I18n.t('sign_out'), destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</div>

<p class="text-info"><%= notice %></p>
<p class="text-error"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :born_in_year %>
    <%= f.input :gender %>
    <%= f.input :topic_keywords %>
    <%= f.input :topic_description %>
    <%= f.input :skype_user %>
    <%= f.input :gmail_address %>
    <%= f.input :sip_address %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Born in year</th>
    <th>Gender</th>
    <th>Topic keywords</th>
    <th>Topic description</th>
    <th>Skype user</th>
    <th>Gmail address</th>
    <th>Sip address</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.name %></td>
    <td><%= participant.email %></td>
    <td><%= participant.born_in_year %></td>
    <td><%= participant.gender %></td>
    <td><%= participant.topic_keywords %></td>
    <td><%= participant.topic_description %></td>
    <td><%= skype_link_to("Call #{participant.skype_user}", participant.skype_user)%></td>
    <td><%= participant.gmail_address %></td>
    <td><%= sip_link_to("Call #{participant.sip_address}", participant.sip_address) %></td>
    <td><%= participant.phone_number %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @participant.name %>
</p>

<p>
  <b>Email:</b>
  <%= @participant.email %>
</p>

<p>
  <b>Born in year:</b>
  <%= @participant.born_in_year %>
</p>

<p>
  <b>Gender:</b>
  <%= @participant.gender %>
</p>

<p>
  <b>Topic keywords:</b>
  <%= @participant.topic_keywords %>
</p>

<p>
  <b>Topic description:</b>
  <%= @participant.topic_description %>
</p>

<p>
  <b>Skype user:</b>
  <%= @participant.skype_user %>
</p>

<p>
  <b>Gmail address:</b>
  <%= @participant.gmail_address %>
</p>

<p>
  <b>Sip address:</b>
  <%= @participant.sip_address %>
</p>

<p>
  <b>Phone number:</b>
  <%= @participant.phone_number %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>